### ISSUE TITLE
String lengths should be limited

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#10]
From @gregquinn2001: Limiting string lengths. Common security concern allowing unlimited length strings in data files. DOD guards always enforce size restrictions in the schemas for the data files. In fact MITRE has a tool that is used to check schemas for security purposes and that’s one of the things it checks.

**Comment by cmoesel** [comment]
From @markkramerus: I’m good with that. We could introduce a length-limited string datatype.  Does FHIR do that?

**Comment by cmoesel** [comment]
I'm not sure we need to introduce a new type.  Could this just be an implementation note that indicates that strings should be no longer than _x_?  If so, what is _x_?

**Comment by gregquinn2001** [comment]
x should be as small as possible is always the DoD answer. Just changing all strings to one common string type with a limit isn't the best approach although narrative type fields may fall back on such a type. Each string should be considered individually for how long it should be maximum. The longer stringer are allowed to be, the more the security threat basically.

**Comment by rutemartins** [comment]
@cmoesel do we have a mechanism to limit string length in CIMPL?

**Comment by cmoesel** [comment]
@rutemartins - not currently.  We wouldn't be able to enforce it much in our framework (except maybe in the ES6 classes) -- since for the most part we don't deal with instance _data_.  We could probably put FHIRPath constraints in the profiles to enforce it -- but I don't really see many people doing that in other profiles.

**Comment by markkramerus** [comment]
Our physical implementation is FHIR, and we follow whatever length limits are in that spec (some string-based data types do have limits).  As Chris says, string length limits are not typically included in IGs.
