### ISSUE TITLE
ER- and PR-specific LOINC codes for NuclearPositivity and AverageStainingIntensity?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#100]
We currently don't have LOINC terms for `NuclearPositivity` and `AverageStainingIntensity`, currently sub-elements of `ProgesteroneReceptorStatus`. We have a couple of options to address this:

**1. Use existing receptor-specific LOINC codes.**
This requires small model changes to make it clear that the elements are now specific to progesterone receptor, e.g. `ProgesteroneReceptorNuclearPositivity`. This may become a bigger issue if we want to use these elements in the context of `EstrogenReceptorStatus`. See issue [#100](https://github.com/standardhealth/shr_spec/issues/101).

**2. Request new, receptor-agnostic LOINC codes.**
Because LOINC codes are test-specific, not general terms, this may be a hard sell, especially since the more specific codes already exist.

**Comment by rutemartins** [comment]
Upon further review, it seems we have already gone down that path for `HER2byIHC`, where `NuclearPositivity` has been replaced with `CompleteMembraneStainingPercent` and the existing LOINC codes have been used.

So now we have `ProgesteroneReceptorStatus` with `NuclearPositivity` and `AverageStainingIntensity` and `HER2byISH` with `CompleteMembraneStainingPercent`. I don't see a reason for these elements not to be modeled in the same way.

**Comment by markkramerus** [comment]
May, what do you think?

**Comment by rutemartins** [comment]
@mlterryMitre, any input?

**Comment by mlterryMitre** [comment]
@rutemartins and @markkramerus - 
If we follow the LOINC survey approach like CAP did, then we could still ask for LOINC codes as it relates to a survey, so that would be Option 2.  
But that's just my opinion.  This is something to delve in deeper for buy-in with the standards community as we get representatives more deeply involved in LOINC committees and the FHIR Orders and Observations WG.  
So maybe option 1 for Sept 2018 ballot and have us work through Option 2?

**Comment by markkramerus** [comment]
I agree #2 is a hard sell.  LOINC for tests is the standard, so we might have to live with the measurement and test method being precoordinated.  Let's double check with SOLOR, if possible, and see whether SOLOR also precoordinates the test with the result. For the ballot, we can use temporary local codes. Does that make sense?

**Comment by markkramerus** [comment]
I checked with Susan Matney, and she agrees with approach #1. In other words, there should be separate LOINC codes for "ER average staining intensity" and "PR average staining intensity".

**Comment by rutemartins** [comment]
Resurfaced in `dev` branch.

**Comment by rutemartins** [comment]
resolved as of commit `52b240aa016781c890539bdffc6d44a17aa640e6` to `dev6`.
