### ISSUE TITLE
Discrepancies between ER status and PR status

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#101]
Is there a reason for not having `NuclearPositivity` and `AverageStainingIntensity` as part of the `EstrogenReceptorStatus`? I know we have method-specific sub-elements, but in the CAP forms the "high-level" element includes these two attributes for both ER and PR, regardless of the information contained in the sub-elements.

**Comment by markkramerus** [comment]
I can't recall why these elements aren't part of ER. So I suppose if we follow CAP, we should add them.

**Comment by rutemartins** [comment]
I checked, and it is there... I momentarily mixed up ER with HER2. No changes necessary.
