### ISSUE TITLE
NuclearPleomorphismScore answers vs. scores

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#109]
Currently we're using [LNC#44645-0](https://s.details.loinc.org/LOINC/44645-0.html?sections=Comprehensive), which has a normative answer list. The list includes answers AND a score for each answer. Not sure if we should stick with the answers only, or if we should capture the scores as well in the model.

**Comment by markkramerus** [comment]
I don't see the problem with answers and scores. Can you elaborate?

**Comment by rutemartins** [comment]
One thing is a score, another is a grade. Currently their conflated in a single answer so you can't use the scores. The answer list has a separate field that matches the answer with a numeric score. I'm wondering if we should consider storing the numeric score separately, so it can be reasoned on (e.g. to calculate the overall score and automatically assign a histologic grade).

This duality of scores vs. descriptions is perhaps better captured in #119, so closing this one.
