### ISSUE TITLE
DiagnosticService for BreastClinicalLymphNodeInvolvement

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#117]
For , we currently have:
```
LaboratoryObservationTopic.DiagnosticService is #exam
```
Why? And why not #pathology?

**Comment by rutemartins** [comment]
Subsumed by #118

**Comment by mlterryMitre** [comment]
DiagnosticService will have #exam for ClinicalLymphNodeInvolvement.  Also, as mentioned in #118 , the final classification is probably best described as the managing physician's evaluation which would be exam.
