### ISSUE TITLE
DiagnosticService for Staging observations

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#118]
We currently have:
```
LaboratoryObservationTopic.DiagnosticService is #laboratory
```
The determination of the TNM *classification* is made by a clinician, and cannot be unequivocally connected to a particular lab result, right? I'm not sure what the right diagnostic service is for this scenario.

Context: I'm reviewing the existing local codes assigned to `LaboratoryObservationTopicDiagnosticService` to align with the FHIR [DiagnosticServiceSections](https://www.hl7.org/fhir/valueset-diagnostic-service-sections.html) value set.

**Comment by mlterryMitre** [comment]
Good point.  The TNM classification is made by the clinician however based on sources that could be clinical, patholological, and by exam so it could be many services.  Perhaps #exam would have been a better choice over laboratory.  Feel free to change it to that instead.

**Comment by rutemartins** [comment]
`DiagnosticService` has `0..*` cardinality, so we can simply delete where it doesn't make sense. However, note that using the `LaboratoryObservation` applies the constraints of `LaboratoryObservationTopic`:

```
Element:		LaboratoryObservationTopic
Based on:	ObservationTopic
Description:	"The topic composition for laboratory observations. A specimen is required, anatomical location is excluded (since the specimen indicates the collection body site). Also includes a diagnostic service (indicating the type of laboratory), not present in general observations."
	1..1	ref(Specimen)
	0..0	AnatomicalLocation  // AnatomicalLocation is where the Specimen was collected
		Category is OBSCAT#laboratory
	0..*	DiagnosticService
```

Since it seems you're inclined to use `OBSCAT#exam` for stating elements, I would say you want to use another class. The only thing `LaboratoryObservation` guives you is a mandatory `Specimen`. Take a look at `cimi_statement.txt` to see what fits best.

**Comment by mlterryMitre** [comment]
Reviewed with @markkramerus and an authoring change of the EntryElement to based on Observation allowed for a change of the category to any of the hl7 observation category options (like exam).

![image](https://user-images.githubusercontent.com/40579130/44093215-df2ca696-9fa0-11e8-882b-92b3b7df8877.png)

This will be released on the next pull request.

**Comment by rutemartins** [comment]
`DiagnosticService` no longer exists in `dev`. This was a CIMI element that did not add value to the model and was eliminated for simplicity.
