### ISSUE TITLE
Do we need DiagnosticService?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#121]
It's optional for `LaboratoryObservationTopic` and it's just cluttering the spec. Is this required for a CIMI-compliant model? Is it just for labs?

**Comment by markkramerus** [comment]
You can get rid of Diagnostic Service if you haven't already done so.

**Comment by rutemartins** [comment]
After discussing a bit more with @markkramerus , we're keeping `DiagnosticService` for pathology lab observations.
