### ISSUE TITLE
Why don't all elements have ExceptionValue defined?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#126]
My understanding is what we're overriding the default `dataAbsentReason` with `exceptionValue`. In the lastest IG build, though, I don't see any elements with `dataAbsentReason`. What am I missing?

**Comment by markkramerus** [comment]
No idea. I haven't done anything on Shimi for some time.

**Comment by rutemartins** [comment]
*Should* every observation have an `exceptionValue` defined? Is that a CIMI requirement? And why is `dataAbsentReason` not showing up on any of the profiles in the IG?

**Comment by rutemartins** [comment]
`ExceptionValue` is the default value mapping to `dataAbsentReason` and it is showing in the profiles in the latest IG build.
