### ISSUE TITLE
Value: code or Coding or CodeableConcept

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#131]
The `Status` element is defined as:

```
Element:	Status
Concept:	MTH#C0449438
Description:	"The current standing or state."
Value:		code or Coding or CodeableConcept
```

The FHIR IG publisher doesn't much like this (see [zulip](https://chat.fhir.org/#narrow/stream/99-IG-creation/topic/Types.20must.20be.20unique.20(code.20vs.20Coding))).  It may be a bug in the publisher, but is this choice really necessary?  Can we just make it a `CodeableConcept`?

**Comment by rutemartins** [comment]
What file is this in, @cmoesel ?

**Comment by cmoesel** [comment]
@rutemartins https://github.com/standardhealth/shr_spec/blob/shimi/spec/cimi_element.txt#L89-L92

**Comment by rutemartins** [comment]
It looks like `Status` is used in `MedicationUsedStatement`, `MedicationDispenseRequestStatement`, `ProcedurePerformedContext`, `ProcedureRequestedContext`, `Composition`, `Encounter`, `EncounterRequestedContext` and `EncounterPerformedContext`.

In all cases it is used with value sets, so using `CodeableConcept` seems reasonable. I'll make the change on the shimi branch.

**Comment by rutemartins** [comment]
@cmoesel this issue will not surface anymore in CIMPL 6.0, correct?
