### ISSUE TITLE
Replace TBD value sets where possible

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#142]
Several elements bind fields to TBD value sets.  These should be replaced or removed before the ballot.

Examples from the _shimi_ branch:

* BreastCancerPrimaryTumorClassification.ObservationContext.ResultValue.CodeableConcept
* BreastCancerRegionalNodesClassification.ObservationContext.ResultValue.CodeableConcept
* BreastCancerDistantMetastasesClassification.ObservationContext.ResultValue.CodeableConcept

**Comment by rutemartins** [comment]
@mlterryMitre is this related to #143 ? I can go in and get rid of the stub value sets, unless you're making changes in these elements.
