### ISSUE TITLE
Stub value set for T, N, and M categories?

### ISSUE THREAD

**Issue by mlterryMitre** [standardhealth/shr_spec#143]
Currently BreastCancerPrimaryTumorClassification, BreastCancerRegionalNodesClassification, BreastCancerDistantMetastasesClassification models could use a stub to an empty value set whose description / comment states that the value set is null and requires the implementer to obtain an AJCC license.
I think we had this somehow in the May 2018 ballot but in our Sept 2018 IGs, valueCodeableConcept doesn't reference anything.

Thoughts on how we should handle this @rutemartins and @markkramerus ?

**Comment by rutemartins** [comment]
I think we just had `Value is CodeableConcept` last time. Not sure a stub value set is good practice... We did allow for more than one staging system, so having a stub value set that points to AJCC defeats that a bit.

**Comment by rutemartins** [comment]
See #142 for resolution.
