### ISSUE TITLE
Broken Link in BreastCancer landing page

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#148]
The landing page has this link: `<a href="StructureDefinition-oncology-BreastCancerPresenceStatement.html">ConditionPresenceStatement profile</a>`.  The FHIR IG Publisher correctly reports it as broken.

I'm a little confused about whether you want to point to the BreastCancerPresenceStatement or the ConditionPresenceStatement (which is the displayed text for the link).  Anyway, depending on which you want, here are the correct relative links to use:

* `StructureDefinition-shr-oncology-BreastCancerPresenceStatement.html`
* `StructureDefinition-cimi-statement-ConditionPresenceStatement.html`

**Comment by rutemartins** [comment]
Despite having been fixed and merged in Aug 2018, the bug persists in the current `dev` branch, I suspect due to some merge conflict along the way. I've seen this with several other issues (open and closed).
