### ISSUE TITLE
Weird syntax in BreastCancerStage

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#168]
I'm seeing:
```
ObservationContext.ResultValue value is type CodeableConcept
ObservationContext.ResultValue should be from http://loinc.org/vs/LL240-3
```
Is `ResultValue value` valid syntax or should it be `ResultValue.value`? Also, it seems it's either `ResultValue.value` or `ResultValue` that should be tied to a value set.

**Comment by cmoesel** [comment]
For the first line, we have special support for the `value is type` construct.  I think it may be the only case where we allow `value` as a separate keyword like this.  I think it _could_ also read `ResultValue._Value is type` instead, if preferred.

For the 2nd, we're allowing the author to be imprecise.  In this case, the tooling recognizes that a VS can't be applied directly to `ResultValue` but that it _can_ be applied to its _value_ (`ResultValue._Value`) -- so the tooling assumes that's what the author wanted and does it.

I think that both of these "features" are now controversial in that they explicitly support or allow for inconsistencies across the grammar.  This type of "special case grammar" (line 1) and "loosey-goosey behavior" (line 2) will likely go away in Grammar 6.
