### ISSUE TITLE
Should specimen be required in LaboratoryObservation?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#190]
`LaboratoryObservation` requires a `specimen` to be present. In some instances we've opted to use `NonLaboratoryObservation` (e.g. `CancerHistologicType`) in order to _evade_ the specimen requirement, since specimen is likely to be missing in laboratory observations across current implementations. This is not optimal because these observations _are_ laboratory observations, and additional constrains typical of `LaboratoryObservation` have to be replicated manually. Some options to address the issue:

* **OPTION 1: Keep specimen as required**, recognizing this may negatively impact adoption since it creates a high barrier of entry.
* **OPTION 2: "Reverse" the specimen in `LaboratoryObservation` sub-classes**. This requires case-by-case consideration, and can be prone to errors. Relaxing a constraint on a parent class, although seemingly allowed, does not strike me as good form.
* **OPTION 3 (my proposal): Relax the current constraint on `LaboratoryObservation` by making `specimen` optional**. This recognizes the current limitations on data availability but supports the inclusion of the data when it is there. Implementing this change will require some effort to cleanup sub-classes.

**Comment by rutemartins** [comment]
@markkramerus, @mlterryMitre, looking for your input.

**Comment by mlterryMitre** [comment]
Option 3.  From a pragmatic implementation perspective, not all lab result interfaces send structured and coded specimen data.

**Comment by markkramerus** [comment]
I don't see any reason that specimen shouldn't be optional in LaboratoryObservation. However, there is a practical difficulty in mapping I need to take care of. Specimen is introduced at the level of Observation just so it can be zeroed out until we get to LabObs. Let me see if I can work around this using the "constrain" mapping keyword instead.

**Comment by markkramerus** [comment]
Fixed this and managed to remove having Specimen on all Observations. It only appears on LabObs right now, and it is 0..1.
