### ISSUE TITLE
Should StageGroup be the FindingResult for CancerStageInformation?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#191]
@markkramerus asked this question in the code. The current modeling stemmed from some discussion between @mlterryMitre and @rutemartins. Knowing that the `CancerStageInformation` element is about more than `StageGroup`, it seems misleading to make `StageGroup` the `FindingResult`. This seems to be one of those instances where the "value" is **not** defining the data element, since it includes, in addition to the overall cancer stage, TNM staging categories.

@markkramerus, any objections or additional considerations?

**Comment by markkramerus** [comment]
I think the class should be renamed to reflect that the result is the stage group. Whether or not the TNM components are present, putting the stage group in the finding result makes most sense and is most consistent with other tests that roll up to a single value, such as Apgar.

**Comment by markkramerus** [comment]
Discussed with May. We've decided the best strategy is to have two observations, one clinical stage group and one pathological stage group. Less confusion.

**Comment by markkramerus** [comment]
FInalized. Stage Group is an observation at the same level as T, N, M.
