### ISSUE TITLE
TNM categories: components vs. panelMembers

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#192]
@markkramerus asked in the code: could TNM categories in `oncologycore CancerStageInformation` be components? Currently, TNM categories are modeled as panel members because they often not concurrently observed. In addition, would we want to reuse the pathological TNM categories in the context of a pathology report? If so, this would support keeping TNM categories as panel members. 

@mlterryMitre any additional insight?

**Comment by markkramerus** [comment]
Agreed. I'm going to call it decided.
