### ISSUE TITLE
GivenName under HumanName in shr_core

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#20]
Based on the description of GivenName under HumanName in shr_core, I think the cardinality should be 0..* instead of 0..1. The description indicates it should be used for both middle and first names in western cultures.

**Comment by markkramerus** [comment]
SHR can be different than FHIR, so if we wanted to have first and middle together "Mark Albert" in the given name slot, we could (they are in fact both given names). But seeing how FHIR does it, I agree to this change. Made in my sandbox (not yet committed).
