### ISSUE TITLE
Add Date and Time of Death to spec

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#21]
One of the attributes suggested for use in patient matching is the date and time of death for a patient. It does have AgeAtDeath but they aren't equal unless age is accurate to a minute which may not be the best way to represent date and time of death?

http://perspectives.ahima.org/wp-content/uploads/2014/12/PatientMatchingAppendixA.pdf

**Comment by markkramerus** [comment]
Done. There is boolean, qualified by one or both of a dateTime and Age in the latest version on the mapping branch.
