### ISSUE TITLE
BodySite.DistanceFromLandmark should allow for specification of the landmark

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#216]
We should be explicit about the landmark we're measuring the distance against, e.g. the nipple in the context of a breast tumor.

**Comment by markkramerus** [comment]
The landmark is the code (and laterality).

**Comment by rutemartins** [comment]
So the code for a BreastSite would be nipple? That doesn't make sense to me.

**Comment by markkramerus** [comment]
Revamped. Now capable of representing the location of the landmark and the type of landmark. The body location is then represented by distance from landmark to body site, and direction from landmark to body site.
