### ISSUE TITLE
Consider adopting FHIR's complex data types

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#31]
We've already fully adopted FHIR's primitive types (e.g., `string`, `code`, `boolean`, etc).  We should consider also adopting FHIR's complex types (e.g., `CodeableConcept`, `Address`, etc).

**Comment by cmoesel** [comment]
Nope.  In CIMPL6 we did move to a new `concept` type -- which isn't _exactly_ one of the FHIR types, but is intended to be compatible with them.  All the other (including `Quantity`) are still defined in CIMPL.  When we implement versioned modules, however, maybe we will have all the CIMPL complex types locked down in a read-only module, and maybe they'll conform to the FHIR complex types.

**Comment by markkramerus** [comment]
There sufficient equivalence now between FHIR and CIMPL (obf-datatype). Closing.
