### ISSUE TITLE
IG Fragment & Template Options

### ISSUE THREAD

**Issue by parisni** [standardhealth/shr_spec#39]
Hi

For now the FHIR documentation your tool generates includes (http://standardhealthrecord.org/fhir/StructureDefinition-shr-encounter-Encounter.html) : 
- text summary
- differential table
- snapshot table
- all

Apparently the IG publishing tool allows to add a bunch of Fragment Codes in the produced documentation.
I d'like by EG to produce an UML box as the official FHIR does to describe the resources. (https://www.hl7.org/fhir/observation.html#tabs-uml)

Have you any idea the way to add them in your code ?   the documentation is not that clear ( http://wiki.hl7.org/index.php?title=IG_Publisher_Documentation#Fragment_.26_Template_Options )

**Comment by parisni** [comment]
I got it. The ig tool generates all the fragment by default. They have to be then referenced by the html templates.
The uml box fragment cannot be generated by design, because of impossibility of rendering slices.

**Comment by cmoesel** [comment]
I'm closing this, at it seems you were able to answer your question.  Please let us know if there is anything we need to look into ourselves.
