### ISSUE TITLE
Should procedure support multiple codes?

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#43]
If a surgery is done I believe that would be modeled as a procedure but multiple things could be done as part of a single surgery. Should procedure support the single code value it does now (which would be surgery in the example I cited) and then support a set of sub-procedure codes for actions taken as part of the single surgery? How should this case be modeled within SHR?

**Comment by markkramerus** [comment]
Leaving this open. I'm not a SME on this... will consult the FHIR oracle and Jonathan Teich.

**Comment by jsnichols** [comment]
"I believe that would be modeled as a procedure" *agree*

"multiple things could be done as part of a single surgery"
*some questions to help define scope here:*
*at what level of detail do you want to capture these 'things'?*
*for what purposes?*
*and with what coding system?*

*"*Should procedure support the single code value it does now (which would
be surgery in the example I cited) and then support a set of sub-procedure
codes for actions taken as part of the single surgery?"
*that's a possibility*
*I would want to understand more about the problem space and consider some
alternatives*

How should this case be modeled within SHR?
*how might we use our ASCO work to learn more about the problem space of
representing procedures?*
*is a radiation treatment a procedure?*
*a mastectomy is an example of a surgery?*
*could we work with radiation oncologists and surgical oncologists to
approach the above issues?*

-JSN-

Joey Nichols
jsnichols@gmail.com
713.398.5225

**Comment by markkramerus** [comment]
I will follow FHIR's lead on this

**Comment by markkramerus** [comment]
The cleanest way to do this is record separate procedures and relate them. Each portion can have different participants. Added "PartOfProcedure" to Procedure.
