### ISSUE TITLE
Typing of conditions/choices in SHR elements

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#49]
A condition has a list of associated observations; however, those observations would be elements or entries? If elements, how do you know what concrete type (subtype of Observation) that each one represents. Problem is larger in cases where a choice exists. How do you know which one of the choices is being used? For example:

Element:		OccurrenceTime
Concept:		TBD
Description:	"The point in time or span of time in which something happens."
Value:			dateTime or date or TimePeriod

If you have an occurrenceTime element, how do you know without inspecting the value whether it is a dateTime, date, or TimePeriod? I think we need to expose types for elements - not just entries (EntryType). I don't think this should be left to implementation as it would result in potential incompatibilities between implementations.

**Comment by markkramerus** [comment]
Chris, this has to do with the instances. Can you discuss with John Gibson? Thanks.

**Comment by gregquinn2001** [comment]
As I said though, I think this should be handled in the spec as we don't want different implementations of typing of elements creating incompatibilities.

**Comment by rutemartins** [comment]
@cmoesel any developments worth noting on this?

**Comment by cmoesel** [comment]
I think this is handled in the JSON-Schema and ES6 classes now (everything declares its type).  I'm not entirely sure what @gregquinn2001 meant by handling it in the spec (beyond what's done now) -- so I can't really comment on that.

**Comment by cmoesel** [comment]
Didn't mean to close it.  Sorry.

**Comment by gregquinn2001** [comment]
As long as we are not afraid that 2 different implementations of the logical model will be incompatible with each other, we'll be ok! Maybe the simplest way I can describe my concern, is as follows. If implementation 1 serialized an instance of an SHR specification. Implementation 1 may decide to type elements in a certain way so it can deserialize them back in. If however, that serialized format went across the wire to implementation 2, how would it know the type of each element represented if the specification doesn't clearly specify how that information will be represented. The serialized format must be completely specified. Maybe it is, but I just want to make sure! Thanks @cmoesel !

**Comment by cmoesel** [comment]
Well... we define two serialization formats: JSON-Schema and FHIR.  The JSON-Schema does formalize how the type should be serialized into the JSON (so it can be distinguished).  The FHIR profile does as well.  So I think we're ok.

**Comment by rutemartins** [comment]
Sounds like we can close this one. Yay!

**Comment by gregquinn2001** [comment]
Thanks @cmoesel and @rutemartins !
