### ISSUE TITLE
Should we have a way to associate conditions to procedures

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#50]
We can put observations within a condition and we can associate conditions with assessments. Should we be able to have a way of linking procedures to conditions? Or maybe linking Actions (Procedure is based on Action) in general to a condition?

**Comment by jsnichols** [comment]
In Medicine, we describe the link between "procedures to conditions" as the
"indication"...

E.g. the presence of a tumor in the breast (condition) indicated the need
for a modified radical mastectomy (procedure)

The "indication" link (procedure to condition) is very important, not only
for patient care, but also for research, quality improvement, billing, etc.

It describes "why we did what we did"

-JSN-

Joey Nichols
jsnichols@gmail.com
713.398.5225

**Comment by gregquinn2001** [comment]
Actually I just found a link between them in the current SHR (onco2 branch). A procedure is based on Intervention which is based on Action which has a Reason element. A Reason (from shr.core) can be string or CodeableConcept or ref(Condition); i.e., a procedure can reference a condition as the reason for the procedure.
