### ISSUE TITLE
Participation in Research Study 

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_spec#54]
Need to represent the clinical trial enrollment for a patient. At minimum this includes the name or id of the clinical trial the patient is enrolled in, the date they were enrolled in the clinical trial, and the date they ended or left the clinical trial. Similar to FHIR's ResearchSubject.

**Comment by markkramerus** [comment]
Maybe something like this:
EntryElement: 	StudyParticipation
Based on:	Participation
Concept:		TBD
1..1			Status from http://hl7.org/fhir/ValueSet/research-subject-status
0..1 			ParticipationType  // constrain
1..1			ref(Study)

**Comment by rutemartins** [comment]
This is currently modeled in the `research` namespace as `ResearchSubject`.
