### ISSUE TITLE
Duplicate subelement name of ClinicallyRelevantTime in Observation

### ISSUE THREAD

**Issue by jafeltra** [standardhealth/shr_spec#56]
In Observation, two subelements are named ClinicallyRelevantTime.

**Comment by markkramerus** [comment]
I don't see this. What branch are you on?

**Comment by gregquinn2001** [comment]
master branch.

EntryElement: 	Observation
Concept:		MTH#C1554188
Based on:		Action
Description:	"An Observation represents evidence, both subjective and objective. Observation includes any information about a subject that results from an act of observing, measuring, or evaluation. The focus of an observation can include the subject's behavior, physiological state, health state, functional status, environment, exposures to substances, etc. An Observation contains information about the act of observing or measuring, and the result of the observation. The method of observing can vary widely, from questioning, physical examination, formal assessment vehicles, laboratory tests, imaging procedures, etc. Patient-reported information is also considered an observation, where subject and observer are the same individual."
Value:			0..1 (Quantity or CodeableConcept could be from ObservationResultVS or string or boolean or Range or Ratio or time or dateTime or TimePeriod)
// TODO: Support additional value types: SampledData or Attachment
//----------- Define the observation to be made
1..1			SpecificType   // inherited from Action, here required
0..*			Category from ObservationCategoryVS if covered
0..1			BodySite  // TODO: this should be 0..* but that doesn't map to FHIR -- This should be part of the 'Focus' of the observation
// TODO: 0..* AdditionalBodySite - observations can involve multiple body sites
//----------- Why this observation is taking place
0..1			Reason
0..1			AssociatedStudy
//----------- Execution of the observation action
1..1			Status from http://hl7.org/fhir/ValueSet/observation-status
				NonOccurrenceModifier.Reason from ObservationNotMadeReasonVS
0..1			Method
//----------- Capture the result and its significance
//				The Value
0..1			AssertionNegationModifier
0..*			ObservationQualifier
0..1			DataAbsentReason
**0..1			ClinicallyRelevantTime  // may not be the same as the OccurrenceTime**
0..*			ReferenceRange
0..1			Interpretation
0..1			Comment
//----------- Related and Sub-Observations
0..1			PanelMembers  // separate observations occurring in a panel
**0..1			ClinicallyRelevantTime**
0..*			Participant 	// TODO: add to metadata?
0..*			Setting
0..*			Location

**Comment by rutemartins** [comment]
In `dev` branch, `ClinicallyRelevantTime` has been replaced with the more general `RelevantTime`, which is not duplicated.
