### ISSUE TITLE
How do we store a photograph of a patient in their SHR?

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#57]
I added a Photograph entry in the demographics namespace for now which just has a file path to an image file. Could also be used for a more generic attachment mechanism for PDFs and imaging results for examples?

**Comment by markkramerus** [comment]
What branch are you on? Did you follow FHIR's approach?

**Comment by gregquinn2001** [comment]
I added it to the object model, not to the spec. I don't know FHIR's approach.

**Comment by markkramerus** [comment]
Added "Headshot" to Person
	Element:		Headshot
	Concept:		TBD
	Description:	"A photograph showing a person's face."
	Value:		Media
