### ISSUE TITLE
How do we capture a Clinical Note in SHR?

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#58]
For now I modeled it as a new entry called ClinicalNote in the core namespace. It can have the content of the note as well as metadata of course like signing clinician and date signed

**Comment by markkramerus** [comment]
Need more information: Is a ClinicalNote always associated an Encounter? Or is it an annotation to a Condition?

**Comment by gregquinn2001** [comment]
I think a ClinicalNote should be able to be associated to an Encounter but shouldn't have to be. I also think it should be able to be associated to a condition, but doesn't have to be. Potentially, it could be associated to a test result as well. We should ask Jonathan and Joey though.

**Comment by rutemartins** [comment]
A `ClinicalNote` EntryElement is now included in the `shr.base` namespace on the dev branch.

**Comment by markkramerus** [comment]
We need to follow US Core on this. See https://build.fhir.org/ig/HL7/US-Core-R4/clinical-notes-guidance.html. The US Core DocumentReference Profile and US Core DiagnosticReport Profile for Report and Note exchange support the exchange of clinical notes. Both can be supported in SHR.
