### ISSUE TITLE
QuestionAnswer -- can the answer be a ref( )?

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr_spec#63]
Employer is posed as a QuestionAnswer (QA), inheriting from Observation. Yet the answer (the Value) is a reference to a Role or Organization (this slipped through because CLI didn't flag an error). 
The issues are: 
1) Do we want QA to allow Value to be a reference type?
2) If the answer to #1 is yes, where does QA inherit from (can't be Observation)?
3) If the answer to #1 is no, then how do we model Employer?

**Comment by rutemartins** [comment]
`Employer` no longer inherits from `Observation` in the current `dev` branch.

**Comment by markkramerus** [comment]
Overcome by events. Closing.
