### ISSUE TITLE
Support for planned encounter with reason

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#68]
Can we add support for planned encounters (appointments) with reason. Current spec has a lot of TBD attributes that look like they might help (HealthConcern?) but I'm not sure. We want to support viewing existing appointments/encounters in Flux Notes for the pre-encounter and post-encounter scenarios. Pre-encounter scenario needs to clearly indicate why the patient is coming in

**Comment by markkramerus** [comment]
We currently have EncounterRequested but not EncounterPlanned. Reason comes from ActionContext, so any flavor of Encounter (Planned, Performed, etc.) will always have a reason
