### ISSUE TITLE
#refused does not accurately reflect intent of code

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#7]
From @gregquinn2001: `#refused` should be `#notanswered` to be more semantically correct. Fixing things that are wrong should be part of the SHR effort. Just because that’s how it’s represented today doesn’t mean it’s right. We should fix it.

**Comment by cmoesel** [comment]
From @markkramerus: Changed to (in my sandbox):
```
#unanswered   "The source was asked, but did not provide the information needed to populate the required entry."
```

**Comment by jsnichols** [comment]
+1


-JSN-

Joey Nichols
jsnichols@gmail.com
443-579-7779
