### ISSUE TITLE
Ki-67 ranged 85% to 95%

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#73]
The sample note we are using for the mid-year demo developed by Joey Nichols with validation from Mark Fairweather notes the patient's Ki-67 ranged 85% to 95%. SHR supports Ki-67 but it looks like it only supports a singular value and not a range.

**Comment by mlterryMitre** [comment]
Change made in git shr_spec [Pull Request #141](https://github.com/standardhealth/shr_spec/pull/141). 
I did find that the reference range appears in the logical model, but not in the FHIR profile.  Not sure if this is a tooling bug.  
Can you check @cmoesel or @markkramerus ?

**Comment by mlterryMitre** [comment]
confirmed the fix and the reference range for Ki-67NuclearAntigenValue in http://build.fhir.org/ig/HL7/us-breastcancer/StructureDefinition-shr-oncology-Ki-67NuclearAntigen.html.  Close issue.
