### ISSUE TITLE
Should Members sub-element of BreastCancerGeneticAnalysisPanel have value which is a list

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#76]
I think the Members sub-element of the BreastCancerGeneticAnalysisPanel  should have a Value that is a list of Observations (possibly could be references to ones as entries as well???). Somewhere it seems there should be a list so I can include BRCA1 and BRCA2 plus the others eventually. If not, the Members declaration within BreastCancerGeneticAnalysisPanel  should not say it should include both BRCA1 and BRCA2.

**Comment by mlterryMitre** [comment]
This is an old comment related to the older breast cancer model. Implications to MCODE are that both BRCA1 and BRCA2 are part of a more generic value set and not specific to a disease at this time.

**Comment by rutemartins** [comment]
Thanks, @mlterryMitre! So we don't expect to constrain that value set set in the `brca` namespace?

**Comment by mlterryMitre** [comment]
At this time, no.  One possibility that was discussed with @markkramerus was to possibly move this outside of the model and in a separate content table, similar to the way SEER does it.  This however is not set in stone and up for debate as we further refine MCODE.

**Comment by rutemartins** [comment]
Thanks for clarifying! Sounds like this issue simply no longer applies. I'll close out.
