### ISSUE TITLE
Study should be supported as a reference to an external entity

### ISSUE THREAD

**Issue by gregquinn2001** [standardhealth/shr_spec#77]
SHR has a Study entry which describes a study such as a clinical trial; however, given that studies are defined outside of patient records (so should not typically be defined within each patient's record), the ResearchSubject entry should support a Study as a sub-element but it should also support a reference to a Study. In addition, the SHR should support the concept of an ExternalReference which would support a REST GET to retrieve the referenced object which exists outside the patient's record. The external reference could be as simple as a URL or be something more complicated.

**Comment by markkramerus** [comment]
RelatedArtifact 0..* can have the study definition and additional information. Aligned with FHIR in this respect.
