### ISSUE TITLE
Pre-Coordinated vs Post-Coordinated Codes

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr_spec#8]
From @gregquinn2001: Allowing pre-coordinated and post-coordinated is counter to SHR goals as I understand them. Supporting multiple ways of representing the same thing is the enemy of clinical interoperability.

**Comment by cmoesel** [comment]
From @markkramerus: I want to take a middle-of-the-road approach. Current practice favors pre-coordinated coding. Analysis loves post-coordinated coding. It will be tough to get from chaos to Nirvana in one step. I think the best strategy is to split the pain between those who do the coding and those who want to reason with the data.

**Comment by gregquinn2001** [comment]
I think we are confusing specification with user interface. Each of them can represent it in their preferred way within their applications built on top of SHR, but to ensure interoperability between those applications, they should both have to represent it the same way under the covers!

**Comment by markkramerus** [comment]
I think we must address this though specifics and profiles. If there are specific instances in SHR (including mCODE) where post-coordination should be enforced, please log them here https://standardhealthrecord.atlassian.net/secure/BrowseProjects.jspa
