### ISSUE TITLE
BreastCancerPresenceStatement: why is MorphologyBehavior VS in entry element?

### ISSUE THREAD

**Issue by rutemartins** [standardhealth/shr_spec#95]
```
BreastCancerPresenceStatement
[...]
0..1 MorphologyBehavior from MorphologyBehaviorVS

Element:		MorphologyBehavior
			Concept: TBD
			Description: "A description of the morphology and behavioral characteristics of the cancer."
			Value: CodeableConcept
```

Why aren't we pointing to the `MorphologyBehaviorVS` from the sub-element? I.e.:

```
Element:		MorphologyBehavior
			Concept: TBD
			Description: "A description of the morphology and behavioral characteristics of the cancer."
			Value: CodeableConcept from MorphologyBehaviorVS
```

**Comment by markkramerus** [comment]
It's there: 0..1			MorphologyBehavior from MorphologyBehaviorVS
Since MorphologyBehavior is a more general concept than breast cancer MB, the binding is on the use of MB in the BreastCancerPresenceStatement. Just a different place to do the binding. There might be pros and cons here.
